/** Domain error codes */
export const ERROR_CODES = {
  WORKER_NOT_ACTIVE: 'WORKER_NOT_ACTIVE',
  BLOCK_NOT_ACTIVE: 'BLOCK_NOT_ACTIVE',
  QUANTITY_MUST_BE_POSITIVE: 'QUANTITY_MUST_BE_POSITIVE',
  RATE_MUST_BE_POSITIVE: 'RATE_MUST_BE_POSITIVE',
  SETTLEMENT_IS_IMMUTABLE: 'SETTLEMENT_IS_IMMUTABLE',
  PAYMENT_EXCEEDS_BALANCE: 'PAYMENT_EXCEEDS_BALANCE',
  WORKER_HAS_PENDING_DEBT: 'WORKER_HAS_PENDING_DEBT',
  CORRECTION_OUTSIDE_WORKDAY: 'CORRECTION_OUTSIDE_WORKDAY',
  SUPERVISOR_NOT_AUTHORIZED: 'SUPERVISOR_NOT_AUTHORIZED',
  DUPLICATE_SETTLEMENT_PERIOD: 'DUPLICATE_SETTLEMENT_PERIOD',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  // Multi-tenant
  ORG_CONTEXT_REQUIRED: 'ORG_CONTEXT_REQUIRED',
  CROSS_TENANT_FORBIDDEN: 'CROSS_TENANT_FORBIDDEN',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
} as const;

/** Pagination defaults */
export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

/** Default branding applied when an organization has none configured */
export const DEFAULT_BRANDING = {
  name: 'Fundo360',
  logo_url: null as string | null,
  brand_primary_color: '#1b5e20',
  brand_secondary_color: '#4caf50',
} as const;
